"""empty message

Revision ID: 7e89295aa97a
Revises: 
Create Date: 2019-11-17 18:47:49.017174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e89295aa97a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=100),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=100),
               nullable=False)
    # ### end Alembic commands ###
